# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190429_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='封面图'),
        ),
    ]
