# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190429_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='../static/images/', verbose_name='封面图'),
        ),
    ]
