# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_front_image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='封面图'),
        ),
    ]
