# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190802_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('TRADE_SUCCESS', '成功'), ('paying', '待支付'), ('TRADE_CLOSE', '交易关闭')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='f_goods',
        ),
        migrations.AlterModelTable(
            name='ordergoods',
            table='f_order_goods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='f_order',
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table='f_shopping_cart',
        ),
    ]
