# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190802_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.OrderInfo', verbose_name='订单详情'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_FINISHED', '交易结束'), ('TRADE_SUCCESS', '成功'), ('WAIT_BUYER_PAY', '交易创建'), ('paying', '待支付'), ('TRADE_CLOSE', '交易关闭')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
